export interface FAQItem {
  id?: number;
  q: string;
  a: string;
}

export const HOME_FAQ: FAQItem[] = [
  { q: "What is the best digital marketing company in Pune for lead generation?", a: "The best digital marketing company in Pune for lead generation should offer a comprehensive mix of high-performance SEO, strategic Google Ads (PPC), Meta Ads, and Conversion Rate Optimization (CRO). At Growthik Media, we specialize in building predictable revenue systems specifically for Pune-based businesses. Unlike traditional agencies that focus purely on vanity metrics like impressions or clicks, our methodology is engineered to drive high-quality inquiries and sales. We combine deep local market insights with advanced tracking through GA4 and GTM to ensure every marketing rupee spent yields a measurable return." },
  { q: "How much does digital marketing cost in Pune for small businesses?", a: "Digital marketing costs in Pune typically vary based on the scope of services, business goals, and competitive landscape. For most small to mid-sized businesses (SMBs) in Pune, monthly retainers generally range from ₹15,000 to ₹50,000. This investment usually covers a focused strategy involving either Local SEO, Google Ads management, or Social Media Marketing. At Growthik Media, we build custom growth plans that align with your specific budget and expansion goals, prioritizing high-impact activities in neighborhoods like Baner, Wakad, and PCMC." },
  { q: "How long until SEO shows measurable results for my Pune business?", a: "SEO is a long-term compound investment. For a typical business in Pune, you can expect to see initial movement in keyword rankings within 4-6 weeks. However, achieving significant, revenue-driving growth usually takes 3 to 6 months of consistent effort. Our strategy focuses on technical excellence, authority building, and local relevance, targeting neighborhood-specific keywords to capture user intent when they are ready to buy." },
  { q: "Which is better for Pune startups: SEO or Google Ads (PPC)?", a: "The choice depends on your timeline. Google Ads (PPC) is ideal for instant visibility and quick lead generation, as ads appear at the top immediately. SEO is a marathon that builds sustainable organic authority, eventually leading to a lower Cost Per Acquisition (CPA). For most successful Pune brands, we recommend an 'omnichannel' approach: use Google Ads to capture demand immediately while simultaneously investing in SEO to build a long-term competitive moat." },
  { q: "Why should I choose a local Pune-based digital marketing agency?", a: "A local Pune agency like Growthik Media has an on-the-ground understanding of regional consumer behavior and neighborhood-specific competition. We know the unique dynamics of areas like Magarpatta, Baner, and Hinjewadi. This allows for face-to-face strategy sessions, quicker communication, and real-time support that national or offshore firms simply cannot match." },
  { q: "What makes Growthik Media's performance marketing different from others?", a: "We focus on 'Growth Engineering' rather than traditional advertising. Every campaign undergoes rigorous A/B testing of headlines, creatives, and landing pages. We utilize advanced server-side tracking and attribution modeling to report on actual bottom-line revenue (ROAS) rather than just vanity metrics like clicks or impressions." },
  { q: "Do you work with small businesses and early-stage startups in Pune?", a: "Yes, we are committed to helping Pune's startup ecosystem. We offer scalable, modular services that grow as you grow. From building high-performance Next.js websites to Local SEO setups that get you on the map, we provide the strategic guidance needed for solo founders in Baner or growing teams in Hinjewadi." },
  { q: "How does local SEO help my business rank in specific Pune neighborhoods?", a: "Local SEO focuses on appearing in the 'Map Pack' for vicinity-based searches in areas like Wakad, Aundh, or Pimpri-Chinchwad. We achieve this by optimizing your Google Business Profile (GBP), ensuring NAP consistency, and generating local reviews, alongside neighborhood-specific landing pages that target hyper-local search intent." },
  { q: "What is your reporting frequency and how do you track marketing ROI?", a: "We provide comprehensive monthly reports detailing KPIs like traffic trends, lead quality, and conversion numbers using GA4 and GTM. We also schedule monthly strategy calls to walk you through the data and plan the roadmap for the following month, ensuring complete alignment on ROI." },
  { q: "Do you provide website development along with digital marketing in Pune?", a: "Yes, we believe a high-converting website is the foundation of any successful campaign. We offer expert design and development using Next.js, React, and WordPress, engineered for speed, mobile responsiveness, and SEO to pass Google's Core Web Vitals out-of-the-box." },
  { q: "How can social media marketing benefit my B2B or B2C brand in Pune?", a: "For B2C brands, platforms like Instagram and Facebook are powerful for visual storytelling and brand building. For B2B firms in Hinjewadi or Magarpatta, LinkedIn is the primary channel for lead generation and professional networking. We create platform-specific content strategies that resonate with your target audience's interests." },
  { q: "What are the common SEO mistakes Pune businesses make?", a: "Common mistakes include neglecting local intent, ignoring page speed, and producing thin or duplicate content. Many brands also fail to optimize their Google Business Profiles or ignore the value of relevant backlinks. We solve these through a 14-step master SEO audit that fixes the technical foundation first." },
  { q: "How do you optimize content for AI search engines like ChatGPT and Perplexity?", a: "We optimize for AI search (GEO) by using structured data (JSON-LD), implementing comprehensive FAQ sections, and focusing on 'E-E-A-T' (Experience, Expertise, Authoritativeness, Trustworthiness). This increases the likelihood of your brand being cited as a primary source in AI-generated answers." },
  { q: "Why is conversion tracking (GTM & GA4) critical for my business?", a: "Proper tracking allows us to see exactly which actions users take on your site, telling us which marketing channels drive revenue and which ones waste money. We set up advanced event tracking for every client to make data-backed decisions that accelerate growth in the Pune market." },
  { q: "How do I get started with Growthik Media for my digital growth?", a: "Simply book a 'Free Strategy Call' or request a 'Digital Audit' through our website. We'll understand your goals, conduct a preliminary audit, and provide a customized 'Growth Roadmap' with no obligation to hire us. We believe in providing value first." },
];

export const SEO_FAQ: FAQItem[] = [
  { q: "What is the best SEO company in Pune for high-competition industries?", a: "Growthik Media is widely regarded as the leading SEO company in Pune for sectors like real estate, healthcare, and IT. Our approach focuses on 'Growth Engineering,' including technical-first optimization, advanced schema markups, and high-authority backlink profiles that outlast algorithm updates." },
  { q: "How long does it take for a Pune SEO company to deliver measurable results?", a: "Measurable SEO results in Pune typically take 3 to 6 months. While technical fixes can show movement within 30 days, sustainable organic growth requires building trust with Google through consistent content hubs and strategic backlink acquisitions." },
  { q: "How much do SEO services in Pune cost for SMBs?", a: "SEO services in Pune for SMBs generally range from ₹15,000 to ₹50,000 per month. At Growthik Media, we provide custom packages tailored to your specific business goals, prioritizing honesty and ROI over one-size-fits-all plans." },
  { q: "What is the difference between Local SEO and National SEO for my Pune brand?", a: "Local SEO targets vicinity-based searches (e.g., 'SEO agency in Baner') and focuses on Google Business Profile optimization. National SEO aims for broad, location-independent keywords across the country, essential for E-commerce or SaaS companies." },
  { q: "How does your 14-step SEO audit system work?", a: "Our proprietary audit deep-dives into server-side configuration, Core Web Vitals, content decay, and internal linking. We fix the technical foundation first to ensure all future marketing efforts are amplified by a technically perfect website." },
  { q: "Is SEO better than Google Ads (PPC) for my Pune-based business?", a: "Neither is objectively 'better'; they serve different purposes. Google Ads (PPC) provides immediate visibility (a 'sprint'), while SEO builds a long-term asset (a 'marathon'). An integrated approach using both often yields the best ROI." },
  { q: "Do you specialize in SEO for specific industries like Real Estate or IT?", a: "Yes, we have specialized frameworks for Real Estate, IT/SaaS, Healthcare, and Education in Pune. We understand industry-specific search behaviors and implement proven strategies that drive genuine growth for these niches." },
  { q: "How can I track the ROI of my SEO campaign with Growthik Media?", a: "We provide custom GA4 dashboards that track actual business outcomes—like phone calls, WhatsApp inquiries, and form submissions—rather than just keyword rankings, ensuring complete transparency on lead generation." },
  { q: "How do you handle the 2026 Google AI Search (SGE/GEO) updates?", a: "We optimize content using structured JSON-LD data and entity-based optimization to ensure AI agents like ChatGPT and Gemini cite your website as a primary source, keeping you ahead as search evolves in 2026." },
  { q: "Do you provide transparent backlink building or 'off-page' SEO?", a: "Yes, we focus on strategic guest posting on niche-relevant sites, digital PR, and broken link building. We provide a full list of acquired links in our monthly reports, ensuring you see the authority-building work being done." },
  { q: "What is an 'SEO Content Hub' and why does my business need one?", a: "An SEO Content Hub is a collection of high-quality content organized around a single topic. This signals absolute authority to Google, making it easier to rank for all related keywords while keeping users on your site longer." },
  { q: "Will you fix technical SEO issues on my website directly?", a: "Yes, our team of growth engineers can implement technical fixes directly on Next.js, WordPress, or Shopify, handling everything from schema injection to fixing Core Web Vitals quickly and correctly." },
  { q: "Why is site speed and Core Web Vitals critical for SEO in 2026?", a: "Site speed is a core ranking factor. A slow site leads to high bounce rates and lost rankings. We optimize performance through modern coding practices, often achieving 90+ Lighthouse scores for our clients." },
  { q: "Do you work with non-Pune businesses for National or International SEO?", a: "Yes, we manage campaigns for clients across India, Singapore, Dubai, and the USA. Our experience in high-competition international markets allows us to bring global-standard strategies to our local Pune clients." },
  { q: "Why should I hire an agency like Growthik Media over a freelancer for SEO?", a: "SEO in 2026 requires a multi-disciplinary team of engineers, writers, and analysts. We provide the stability, professional reporting, and enterprise-level tools that freelancers typically cannot offer." },
];

export const PPC_FAQ: FAQItem[] = [
  { q: "Why should I hire a Google Ads agency in Pune instead of managing it myself?", a: "A professional agency prevents 'budget bleed' by optimizing Quality Scores, lowering Cost-Per-Click (CPC), and performing surgical negative keyword scrubbing. We stay ahead of algorithm updates and use advanced bidding strategies to ensure you pay less than competitors for top-of-page visibility." },
  { q: "How long does it take to see results from a Google Ads (PPC) campaign?", a: "Google Ads offers immediate results. You can start seeing qualified inquiries within 48-72 hours of launching. While we refine bidding over the first 30 days to improve performance, the initial lead flow starts almost instantly after the ads go live." },
  { q: "How much does Google Ads management cost in Pune?", a: "Management fees in Pune typically range from ₹15,000 to ₹75,000 per month. At Growthik Media, we offer flexible pricing models and focus on providing a positive ROAS so that our fees are effectively covered by the additional revenue generated." },
  { q: "Do you specialize in local Pune targeting, like Hinjewadi or Baner?", a: "Yes, hyper-local targeting is a core strength. We use geo-fencing and radius targeting to show ads only to users in specific neighborhoods or near landmarks like EON IT Park, ensuring your budget is spent on high-intent local users." },
  { q: "How do you track 'Conversions' and ROI for Google Ads?", a: "We use a multi-layered setup with GTM and GA4 to capture every valuable action—calls, WhatsApp inquiries, and form submissions. This allows us to scale winning keywords and cut losers, ensuring your budget moves toward the highest-performing segments." },
  { q: "Will you build custom landing pages for my Google Ads campaigns?", a: "Yes, we build high-performance Next.js landing pages designed to align with your ad copy. These pages load instantly and use conversion psychology to lower your CPC and increase your overall conversion rates." },
  { q: "Why is my CPC so high, and how can you lower it?", a: "High CPCs are often due to low Quality Scores or broad keyword bidding. We lower your CPC by optimizing ad copy, keyword relevance, and landing page speed, helping you win auctions at a lower price and get more leads for the same budget." },
  { q: "Do you manage both Search Ads and Performance Max (PMax)?", a: "Yes, we manage Search, Display, YouTube, Shopping, and Performance Max (PMax) ads. We use Search for high-intent B2B demand and PMax for broad e-commerce reach, always providing manual overrides to ensure optimal ROI." },
  { q: "What is 'Remarketing' and why does my Pune business need it?", a: "Remarketing shows ads to previous website visitors who didn't convert. Since many users need multiple touchpoints before a decision, remarketing keeps you top-of-mind and significantly increases your overall conversion rate." },
  { q: "How do you handle 'Negative Keywords' to save my ad budget?", a: "We conduct weekly Search Term Audits to filter out irrelevant queries like 'free' or 'jobs.' This constant scrubbing ensures 100% of your budget is directed toward high-intent 'Money Keywords' that lead to conversions." },
  { q: "What is a 'Good' ROAS (Return on Ad Spend) for a Pune business?", a: "A 'good' ROAS varies but we typically aim for 4x to 8x for e-commerce. We calculate your break-even ROAS and set realistic targets to ensure sustainable, profitable scaling for your advertising efforts." },
  { q: "Can I see my Google Ads account and own the data?", a: "Yes. We believe in 100% transparency and account ownership. We set up campaigns within your account or provide full admin access, so you own all data, history, and structures at all times." },
  { q: "How do you optimize Google Ads for mobile users in Pune?", a: "With 80% of traffic on mobile, we create mobile-only ad variations and 'Click-to-Call' extensions. We ensure landing pages are mobile-first and load instantly, capturing the high volume of local on-the-go searchers in Pune." },
  { q: "What is your process for testing and refining ad copy?", a: "We use scientific A/B testing, running multiple variations of Responsive Search Ads simultaneously. We manually review asset performance weekly and replace low-performing headlines based on psychological triggers to maximize CTR." },
  { q: "Why should I choose Growthik Media over a large, national PPC firm?", a: "Large firms often treat mid-sized accounts as numbers. We provide senior-level expertise, an intimate understanding of the Pune market, and obsessive attention to detail that is required to win competitive search auctions." },
];

export const SOCIAL_FAQ: FAQItem[] = [
  { q: "Why should my Pune-based business invest in professional social media marketing?", a: "Social media is now a critical customer acquisition channel. We help you move beyond random posting to a strategic 'Content Matrix' that builds community, establishes authority, and drives measurable traffic to your website." },
  { q: "Which social media platforms are best for Pune startups and businesses?", a: "For B2C brands, Instagram and Facebook are essential. For B2B firms and IT companies, LinkedIn is king. we build platform-specific strategies—using Reels for Instagram and thought-leadership for LinkedIn—to maximize impact." },
  { q: "How do you measure the ROI of social media marketing in Pune?", a: "We track conversion metrics like profile visits, website clicks, and actual leads generated. By using UTM parameters and GA4, we translate social engagement into business outcomes and provide monthly ROI reports." },
  { q: "Do you handle 'Reel' production and visual content creation for Pune brands?", a: "Yes, vertical video is the most effective way to gain reach. We provide end-to-end production, scriptwriting, and editing, incorporating local landmarks to make content relatable to the Pune audience." },
  { q: "How much does social media management cost in Pune for SMEs?", a: "Management starts from ₹15,000 for basic posting and can go up to ₹75,000+ for comprehensive strategies. We create custom packages based on platform count and content frequency." },
  { q: "What is the difference between organic social media and paid social ads?", a: "Organic is for building long-term relationships and authority. Paid ads allow you to skip the line and target new audiences immediately. We recommend a hybrid strategy for the best results." },
  { q: "How do you manage community engagement and comments for your clients?", a: "We actively monitor profiles for comments and messages, responding within hours to turn casual commenters into leads using a professional brand voice aligned with your values." },
  { q: "Do you provide LinkedIn marketing for B2B companies in Pune's IT hubs?", a: "Yes, we specialize in LinkedIn Page management and Personal Branding for CEOs and executives, using data-led infographics and thought-leadership posts to position you as an expert in your niche." },
  { q: "How often should my Pune business post on social media for maximum reach?", a: "Consistency is key. We recommend 3-5 high-quality posts per week. We prioritize quality over quantity, as one viral Reel is worth more than ten generic stock photos." },
  { q: "Do you handle influencer marketing and local Pune collaborations?", a: "Yes, we identify and collaborate with local Pune influencers who have genuine regional followings, handling everything from outreach to negotiation and creative briefing for instant credibility." },
  { q: "What is a 'Content Pillar' strategy and why is it important?", a: "Content Pillars are 3-5 core themes that align with your brand expertise. This consistency help both platform algorithms and followers understand your brand, leading to higher engagement and better recall." },
  { q: "Can social media marketing help with my website's SEO?", a: "High social engagement drives website traffic, signaling value to Google. Social profiles also often rank on the first page of search results, increasing your brand's overall digital real estate." },
  { q: "How do you keep up with social media trends and algorithm changes?", a: "We analyze platform updates and trend reports weekly. For Pune clients, this means we can quickly pivot tactics—like shifting to Carousels or Reels—as soon as algorithms change priority." },
  { q: "Do I need to be 'on camera' for my business's social media?", a: "While helpful for trust, it's not a requirement. We can create effective campaigns using high-quality B-roll or motion graphics. We can also help guide you through the process if you want to be on camera." },
  { q: "Why should I choose Growthik Media over a lone social media freelancer?", a: "A freelancer can post, but we engineer growth. You get a full team—strategist, designer, editor, and copywriter—ensuring social is a integrated revenue-generator, not just a necessary expense." },
];

export const WEB_DEV_FAQ: FAQItem[] = [
  { q: "Why is Growthik Media considered the best website development company in Pune?", a: "We focus on 'Performance Engineering' using Next.js and React. Our websites aren't just brochures; they are high-speed revenue engines that pass Core Web Vitals with 90+ Lighthouse scores out-of-the-box." },
  { q: "What is Next.js, and why do you recommend it for Pune businesses?", a: "Next.js allows for superior speed and automatic SEO optimization through server-side rendering. This provides a massive edge for ranking in competitive Pune business hubs like Baner or Hinjewadi." },
  { q: "How much does a professional business website cost in Pune?", a: "Costs vary by complexity. WordPress sites start from ₹25,000, while custom Next.js applications range from ₹65,000 to ₹2,50,000+. We focus on delivering a high ROI and a strategic digital asset." },
  { q: "How long does it take to develop a custom website for my Pune startup?", a: "A standard corporate site takes 4-8 weeks. Complex applications take 10-16 weeks. We follow a structured process from wireframing to deployment, prioritizing launching an MVP to start lead generation quickly." },
  { q: "Do you specialize in e-commerce website development for Pune retail brands?", a: "Yes, we build high-converting sites on Shopify, WooCommerce, and headless commerce solutions, integrating local payment gateways and automated shipping to handle high festival traffic spikes." },
  { q: "Will my website be mobile-responsive and pass Core Web Vitals?", a: "Absolutely. We follow a mobile-first philosophy and optimize for Google's Core Web Vitals to ensure better rankings and lower bounce rates for the 80% of Pune traffic coming from mobile devices." },
  { q: "Do you provide website maintenance and support in Pune?", a: "Yes, we offer monthly maintenance plans for security patches, performance monitoring, and updates. We act as your long-term technical partners to keep your site aligned with your marketing strategy." },
  { q: "Can you build custom web applications and SaaS platforms?", a: "Yes, we specialize in building complex, data-driven applications using modern stacks like MERN or Next.js with Supabase, capable of handling thousands of concurrent users with high security." },
  { q: "How do you handle technical SEO and schema markup during development?", a: "We integrate technical SEO into the site architecture, implementing advanced JSON-LD data and optimizing heading hierarchies and site maps to ensure your new site ranks faster for Pune keywords." },
  { q: "Do you provide UI/UX design along with web development in Pune?", a: "Every project starts with a UI/UX phase in Figma. Our designs are based on conversion psychology, ensuring layouts guide Pune users toward your primary call to action intuitively." },
  { q: "Can I manage the website content myself after it's launched?", a: "Yes, we build with user-friendly CMS options like WordPress or Contentful and provide custom training sessions so you can update text and images without any coding knowledge." },
  { q: "Do you offer web hosting and domain registration services?", a: "We manage hosting on premium platforms like Vercel and AWS for 99.9% uptime and handle domain/email setup, providing a complete turnkey solution for your Pune business's digital presence." },
  { q: "How do you ensure the security of the websites you develop?", a: "We use SSL encryption, advanced firewalls, and framework-level security to prevent common attacks. Custom Next.js builds provide a smaller attack surface, making your site more resilient to hackers." },
  { q: "What is your process for integrating third-party APIs and CRMs?", a: "We have extensive experience integrating tools like Hubspot and Zoho CRM, ensuring every lead generated is automatically synced with your sales workflow, turning your site into a business hub." },
  { q: "Why should a local Pune business choose Growthik Media over a national firm?", a: "As a Pune-based agency, we understand the local market dynamics and provide personalized, on-the-ground support that national firms cannot match, ensuring your digital experience matches local expectations." },
];

export const CONTENT_MARKETING_FAQ: FAQItem[] = [
  { q: "Why is content marketing essential for Pune-based B2B and IT companies?", a: "For B2B and IT firms in Pune hubs like Hinjewadi and Magarpatta, content marketing is the primary driver of 'Authority.' Decision-makers don't just buy services; they buy expertise. By producing high-quality whitepapers, case studies, and technical blogs, you position your brand as a thought leader. This makes the sales process much easier, as potential clients already trust your expertise before they even get on a call with you." },
  { q: "How does Growthik Media create a content strategy for Pune businesses?", a: "We use a proprietary framework called 'The Authority Matrix.' We start by identifying your target audience's deepest pain points and search intent. We then map out content pillars that address these needs across the entire buyer journey—from Awareness to Action. For a Pune business, this means creating content that is locally relevant yet globally authoritative, ensuring your brand stands out in a crowded digital landscape." },
  { q: "What types of content do you produce for your clients in Pune?", a: "We produce a wide range of assets including SEO-driven blog posts, lead-generating whitepapers, 'hero' videos, case studies, LinkedIn thought-leadership articles, and email newsletters. For our Pune clients, we focus on 'High-Value' content that provides genuine utility to the reader. Whether it's a guide to real estate investment in Baner or a technical deep-dive into AI for IT firms, we ensure every piece of content serves a specific business goal." },
  { q: "How long does it take for content marketing to show results?", a: "Content marketing is a compound investment. While you can see immediate engagement from social distribution or newsletters, significant organic traffic growth typically takes 4 to 9 months. However, the 'Trust Factor' increases almost immediately. A single high-quality case study can help close a deal in week one, providing a direct ROI even before the SEO benefits fully kick in." },
  { q: "How much does content marketing cost in Pune for startups and SMEs?", a: "Content marketing costs in Pune typically start from ₹20,000 to ₹60,000 per month for managed strategies. This usually includes a mix of content creation, SEO optimization, and distribution. At Growthik Media, we focus on 'Zero-Waste' content—every piece we create is designed to be repurposed across multiple channels, maximizing your investment's value." },
  { q: "How do you measure the success of a content marketing campaign?", a: "We look beyond simple 'page views.' We track engagement metrics like time on page and scroll depth, and conversion metrics like newsletter signups or contact form submissions. For our Pune clients, we also monitor brand mentions and backlink growth, attributes that directly contribute to increasing your revenue." },
  { q: "Do you handle content distribution and promotion as well?", a: "Yes, great content is useless if nobody sees it. We follow a '1:5 Rule'—for every hour we spend creating content, we spend five promoting it. We distribute your content through optimized social media posts, email marketing, and strategic internal linking, leveraging LinkedIn outreach for our Pune B2B clients." },
  { q: "What is 'Lead Magnet' creation and why does my business need it?", a: "A Lead Magnet is a high-value piece of content—like an E-book or Industry Report—that you give away in exchange for contact information. This is critical for Pune businesses with long sales cycles, allowing you to 'nurture' leads through email automation until they are ready to purchase." },
  { q: "How do you ensure the content reflects my brand's unique voice?", a: "We begin every partnership with a 'Voice and Values' workshop. We create a 'Style Guide' that our writers follow to ensure every piece of content feels like it was written by your internal team, incorporating local cultural nuances and professional terminology specific to your industry." },
  { q: "Can content marketing help improve my website's SEO rankings?", a: "Content is the 'gasoline' that powers your SEO engine. High-quality, long-form content is more likely to rank for complex queries and attract natural backlinks. By publishing authoritative content, we sign to Google that your Pune business is a primary source of information, leading to higher rankings." },
  { q: "Do you provide case study writing for Pune's service-providers?", a: "Yes, case studies are powerful conversion tools. We showcase specific projects in locations like Baner or Kharadi, providing 'Social Proof' that resonates deeply with local and international prospects alike." },
  { q: "How do you keep content fresh and relevant over time?", a: "We practice 'Content Lifecycle Management,' regularly auditing and updating existing content to reflect new data or better keywords. We ensure your content remains evergreen, continuing to attract and convert leads years after it was first published." },
  { q: "What is the role of 'Thought Leadership' in content marketing?", a: "Thought leadership moves you from 'vendor' to 'expert.' We ghostwrite articles for your CEOs that demonstrate deep understanding of market trends, making your brand the preferred choice for high-value partnerships in Pune's tech and manufacturing sectors." },
  { q: "Do you use AI to write content for your clients?", a: "We use AI for research and outlining, but every final piece is written and polished by human experts. This ensure your content is optimized for search engines while remaining deeply engaging and authentic for your Pune audience." },
  { q: "Why should I choose Growthik Media for content marketing over a freelance writer?", a: "A freelancer can write words, but we engineer growth. You get a full team—strategist, SEO expert, professional writer, and distribution specialist—ensuring every piece of content leads to measurable business outcomes." },
];

export const LEAD_GEN_FAQ: FAQItem[] = [
  { q: "How does Growthik Media's lead generation strategy differ from traditional agencies in Pune?", a: "Traditional agencies often deliver 'Lead Volume' without 'Lead Quality.' At Growthik Media, we build 'Revenue Systems.' We use advanced lead scoring and intent-based targeting to ensure you spend time only on high-value prospects, maximizing your Pune brand's revenue." },
  { q: "How long until we start seeing qualified leads for our Pune business?", a: "With paid strategies, initial inquiries start within 3-5 days. Organic lead generation takes 3-6 months. We focus on 'Low-Hanging Fruit' first, targeting high-intent keywords that bring qualified traffic quickly." },
  { q: "Do you provide lead generation for B2B companies in Hinjewadi or Baner?", a: "Yes, B2B lead generation is a core specialty. We focus on LinkedIn Ads, professional content marketing, and strategic email sequences that reach decision-makers in Pune's IT hubs like Hinjewadi and Magarpatta." },
  { q: "What is your process for 'Lead Nurturing' and why is it important?", a: "Lead nurturing involves using automated email sequences and remarketing to stay top-of-mind. We build workflows that provide value over time, moving prospects closer to a purchase decision and increasing conversion rates." },
  { q: "Can you help integrate leads directly into our CRM?", a: "Absolutely. We sync every lead with your CRM (Zoho, HubSpot, Salesforce) instantly, setting up custom fields and notifications so your Pune sales team can follow up while the lead is hot." },
  { q: "How much does a lead generation campaign cost in Pune?", a: "Costs vary, but we recommend starting with a combined management fee and a dedicated ad spend budget. We focus on achieving a positive ROI quickly so the campaign becomes a self-funding growth engine." },
  { q: "Do you specialize in lead generation for high-value sectors like Real Estate?", a: "Yes, we have deep experience in Pune's Real Estate sector in areas like Baner and Wakad. We use hyper-local geo-targeting and automated WhatsApp integrations to capture high-intent property buyers." },
  { q: "What is the role of landing pages in lead generation results?", a: "A high-performing landing page is critical. We build custom Next.js landing pages that align with your ad copy, using conversion psychology and clear CTAs to guide users into taking action immediately." },
  { q: "How do you track and report on 'Lead Quality' effectively?", a: "We look beyond form submissions, tracking Sales-Qualified Leads (SQLs) and actual deals. Using GA4, we attribute these results back to specific campaigns, ensuring complete transparency for your Pune brand." },
  { q: "Do you handle Meta (Facebook/Instagram) Lead Ads?", a: "Yes, Meta Lead Ads are excellent for B2C consumer services in Pune. We design thumb-stopping creatives and use strategic behavior targeting to capture leads directly within the social platforms." },
  { q: "Is SEO a viable strategy for long-term lead generation?", a: "SEO is the ultimate long-term asset. Organic leads often have the highest trust and lowest acquisition cost. We focus on building 'Topical Authority' for your Pune brand to ensure long-term visibility." },
  { q: "What is a 'Predictable Revenue System'?", a: "It's a data-led engine that consistently delivers a known number of qualified leads for a specific investment. We build this by diversifying lead sources and ruthlessly optimizing every step of your marketing funnel." },
  { q: "Do you help with lead generation for international expansion?", a: "Yes, we help Pune-based firms expand into the USA, Singapore, and Dubai. We localize ad copy and implement global SEO strategies that allow you to compete effectively on a world stage." },
  { q: "How do you handle 'Cold Outreach' vs 'Inbound Lead Gen'?", a: "Inbound captures demand, while cold outreach targets 'Dream Clients.' We believe in a hybrid approach for Pune businesses to maximize their sales pipelines and capture every possible growth opportunity." },
  { q: "Why should I choose Growthik Media for lead generation?", a: "We aren't just a lead gen firm; we are a full-stack growth partner. We handle everything from technical tracking to CRM integration and lead nurturing, ensuring every lead has the highest chance of converting." },
];

export const LOCAL_SEO_FAQ: FAQItem[] = [
  { q: "What is Local SEO and why is it critical for my Pune business?", a: "Local SEO optimizes your digital presence to dominate searches within specific Pune neighborhoods like Baner, Hinjewadi, or Magarpatta. Statistics show that 46% of all Google searches have local intent. If you're not in the 'Map Pack' Top 3, you're losing high-intent customers who are literally standing near your storefront or office." },
  { q: "How long until my business ranks on Google Maps in Pune?", a: "While technical optimization of your Google Business Profile (GBP) can show results in 2-4 weeks, consistently ranking for high-volume keywords in competitive areas like Kothrud or Wakad usually takes 3 to 6 months of active management, including citation building and review velocity." },
  { q: "What are the most important factors for ranking in Pune's local search?", a: "Google uses three primary pillars: Relevance (how well you match the search), Distance (how close you are to the user), and Prominence (your online authority). We optimize all three by managing your GBP, acquiring local Pune-based backlinks, and implementing neighborhood-specific content strategies." },
  { q: "Do you provide Local SEO services near DMart Warje or Hinjewadi IT Park?", a: "Yes, we specialize in hyper-local targeting near major Pune landmarks. Whether your customers are near DMart Warje, EON IT Park, or Balewadi High Street, we ensure your business is the first one they see on their smartphone." },
  { q: "How do you handle Google Business Profile suspensions?", a: "Suspensions are common in competitive Pune markets. We have a dedicated reinstatement process that ensures your listing follows all compliance guidelines. We help you fix the root cause and work directly with Google support to get your business back on the map." },
  { q: "What is the cost of Local SEO services in Pune?", a: "Our Local SEO management starts from ₹12,000 per month. This investment covers GMB management, local citation building, and review acquisition strategies that typically deliver a far higher ROI than traditional local advertising like newspapers or hoardings." },
  { q: "How does AEO (Answer Engine Optimization) impact local business in 2026?", a: "AI agents like ChatGPT and Google's AI Overviews now pull local data to answer user questions. We optimize your JSON-LD schema and GBP content to ensure these AI engines recommend your Pune business as the best local provider." },
  { q: "Do reviews really impact my local ranking in Pune?", a: "Absolutely. Review volume, velocity, and 'sentiment' are major ranking factors. We help you implement ethical systems to gather authentic 5-star reviews from your Pune customers, significantly boosting your map visibility and trust." },
  { q: "What is NAP consistency and why should I care?", a: "NAP stands for Name, Address, and Phone number. Inconsistency across Punes local directories (like Justdial or Sulekha) confuses Google and hurts your rankings. We perform thorough audits to ensure your business data is 100% identical everywhere online." },
  { q: "Can I target multiple Pune neighborhoods with one website?", a: "Yes, through 'Local Landing Pages.' We build fast-loading, neighborhood-specific pages for areas like Aundh, Viman Nagar, and Hadapsar, each optimized for local keywords to capture searchers in those specific vicinities." },
  { q: "What is a 'Local Citation' and how do you build them?", a: "A local citation is any mention of your business on regional Pune websites or business directories. We focus on high-quality, relevant directories that signal to Google that your brand is a legitimate and prominent local entity." },
  { q: "How do you track the success of a Local SEO campaign?", a: "We track 'Real-World Results': phone calls, direction requests on Google Maps, and website clicks from local searchers. We provide custom dashboards that show exactly how many new Pune customers found you via local search." },
  { q: "Why should I choose Growthik Media over a generic SEO agency in Pune?", a: "Generic SEO ignores geography. We are growth engineers who understand the unique neighborhood dynamics of Pune. We combine technical SEO expertise with an on-the-ground understanding of where your local customers are actually searching." },
  { q: "Does my business need a physical office for Local SEO to work?", a: "While a physical address helps for Google Maps, 'Service Area Businesses' (like plumbers or consultants) can also rank highly in Pune by defining their service radius correctly within their Google Business Profile." },
  { q: "How do I get started with a local SEO audit for my Pune company?", a: "Just request our 'Free Local Audit.' We'll analyze your current Map Pack position, check for NAP errors, and provide a 3-month roadmap to dominate your local Pune neighborhood." },
];

export const META_ADS_FAQ: FAQItem[] = [
  { q: "Why should I run Meta (Facebook & Instagram) Ads for my Pune business?", a: "Meta Ads allow hyper-precise targeting by location, interest, and behavior. For Pune brands, this means reaching potential customers in Baner, Kothrud, or Hinjewadi with surgical precision, driving leads at a fraction of the cost of traditional media." },
  { q: "How much should I budget for Meta Ads in Pune?", a: "A starting budget of ₹5,000–₹15,000/month in ad spend is viable for local SMBs. For scaling lead generation, ₹30,000–₹1,00,000/month is more effective. We focus on ROAS, ensuring every rupee generates measurable returns." },
  { q: "What is the difference between Facebook Ads and Instagram Ads?", a: "Facebook excels at reaching decision-makers aged 30-55 and driving website traffic. Instagram dominates visual storytelling and younger demographic engagement. We run integrated campaigns across both platforms for maximum reach in the Pune market." },
  { q: "How do you target specific audiences for Meta Ads in Pune?", a: "We use detailed targeting including location pins around key Pune areas, interest-based communities, lookalike audiences from your existing customer list, and behavioral patterns to ensure ads are shown only to your ideal customer profile." },
  { q: "What is a Meta Pixel and why is it critical for my campaigns?", a: "The Meta Pixel is a tracking code that records visitor actions on your website. It powers remarketing, conversion tracking, and lookalike audiences. Without it, you're flying blind. We set up and verify the pixel correctly from day one." },
  { q: "How long does it take to see results from Meta Ads?", a: "While initial impressions happen within hours of launching, the campaign typically needs 7-14 days in the 'Learning Phase' before the algorithm optimizes delivery. We see consistent, scalable results after 30-60 days of active management." },
  { q: "Can Meta Ads work for B2B companies in Pune's IT sector?", a: "Yes, though LinkedIn is primary for B2B, Meta Ads are highly effective for reaching IT professionals in Hinjewadi during their personal browsing. We combine interest and job title targeting to reach relevant B2B decision-makers on Facebook." },
  { q: "What ad formats do you create for Meta campaigns?", a: "We create a diverse creative mix: single image ads, video ads, carousel ads showing multiple services, collection ads for e-commerce, and Reels for Instagram. Our design team creates thumb-stopping visuals tailored to the Pune audience." },
  { q: "Do you handle creative (images and videos) for Meta Ads?", a: "Yes, we provide full creative production. Our team designs high-converting ad creatives, writes compelling ad copy using psychological triggers, and continuously A/B tests different variations to find the best-performing assets for your Pune brand." },
  { q: "How do you prevent 'ad fatigue' and keep campaigns fresh?", a: "We implement creative rotation, refreshing ad sets every 2-3 weeks. We monitor frequency metrics closely and introduce new creative angles to prevent audience fatigue, ensuring your cost-per-result stays low over time." },
  { q: "What is Retargeting and why is it essential for Pune businesses?", a: "Retargeting shows ads to people who visited your site but didn't convert. Since most users require 3-7 touchpoints before acting, retargeting is one of the lowest-cost, highest-ROI strategies available, especially for Pune's competitive local market." },
  { q: "Do you manage WhatsApp Lead Ads through Meta Business Suite?", a: "Yes, we set up 'Click to WhatsApp' campaigns that drive direct conversations. This is extremely effective for Pune businesses where WhatsApp is the preferred communication channel for inquiries and follow-ups." },
  { q: "How do you report on Meta Ads performance?", a: "We provide custom monthly reports covering Reach, Impressions, CPM, CTR, CPL, and actual Revenue/ROI. We use GA4 UTM attribution alongside Meta Insights to give you the complete, truthful picture of your campaign's impact." },
  { q: "Is it possible to run Meta Ads with a very small budget for a local Pune shop?", a: "Yes. Even ₹2,000-₹5,000/month can be highly effective for hyper-local campaigns targeting a 5km radius around your physical store location in areas like Warje or Kothrud when set up correctly." },
  { q: "Why should I choose Growthik Media for Meta Ads over a freelancer?", a: "You get a full team of strategists, designers, and analysts. We bring proven frameworks from managing campaigns across multiple industries, providing enterprise-level execution with personal attention to your Pune brand's goals." },
];

export const ECOMMERCE_FAQ: FAQItem[] = [
  { q: "Why is Growthik Media the best e-commerce development agency in Pune?", a: "We don't just build shops; we build conversion engines. We specialize in Shopify and Next.js commerce, focusing on ultra-fast load times, secure payment integrations, and automated inventory systems that help Pune retail brands scale profitably." },
  { q: "Which platform is better for my Pune brand: Shopify or WooCommerce?", a: "Shopify is ideal for brands wanting a hands-off, managed solution with high reliability. WooCommerce is better for those needing deep customizability and who already use WordPress. We help you choose based on your specific SKU count and growth plans for the Pune market." },
  { q: "How much does e-commerce website development cost in Pune?", a: "A professional e-commerce site starts from ₹45,000 for a curated Shopify store and can go up to ₹3,00,000+ for custom headless commerce builds. We focus on creating a strategic asset that pays for itself through increased sales." },
  { q: "How long does it take to launch an online store in Pune?", a: "A standard Shopify store can be launched in 3-5 weeks. Custom builds take 8-12 weeks. We follow an agile process, prioritizing a 'Minimum Viable Store' so you can start accepting orders from Pune customers as quickly as possible." },
  { q: "Do you integrate local Pune payment gateways like Razorpay or CCAvenue?", a: "Yes, we handle the full integration of Indian payment gateways, including Razorpay, PayU, and CCAvenue. We ensure secure transactions and automated receipt generation for your customers." },
  { q: "Will my e-commerce site be mobile-optimized for Pune shoppers?", a: "Absolutely. With 85% of e-commerce traffic in Pune coming from mobile, we follow a mobile-first design philosophy, ensuring checkout is fast, simple, and friction-less on all smartphone devices." },
  { q: "How do you handle e-commerce SEO during the development phase?", a: "We build SEO into the foundation. This include optimized URL structures, schema markup for products (Price, Availability, Reviews), and ultra-fast load speeds that help you rank for competitive Pune retail keywords." },
  { q: "Do you provide inventory and shipping automation services?", a: "Yes, we integrate your store with shipping aggregators like Shiprocket or Delhivery. This automates label printing and tracking notifications, saving you hours of manual work every day." },
  { q: "How do you ensure the security of my online store and customer data?", a: "Security is non-negotiable. We implement SSL encryption, PCI-compliant checkout processes, and advanced firewalls. For custom builds, we use secure modern frameworks that minimize the attack surface for your Pune brand." },
  { q: "Can you help migrate my store from an old platform to a new one?", a: "Yes, we specialize in seamless migrations. We move your products, customers, and order history while ensuring your SEO rankings are preserved through strategic 301 redirects." },
  { q: "What is 'Headless Commerce' and is it right for my Pune business?", a: "Headless commerce separates the frontend from the backend, providing ultimate speed and design flexibility. It's ideal for high-growth Pune brands wanting a unique, app-like shopping experience that stands out from the competition." },
  { q: "Do you provide ongoing support and maintenance for e-commerce sites?", a: "Yes, we offer monthly retainers for security updates, performance monitoring, and adding new features, acting as your dedicated technical partner as your business grows." },
  { q: "Can you build multi-vendor marketplaces like Amazon or Etsy?", a: "Yes, we can build custom multi-vendor platforms that allow multiple sellers to list products, manage their own shops, and receive automated payouts, all from a central Pune-based hub." },
  { q: "How do you optimize checkout pages to reduce cart abandonment?", a: "We use conversion psychology to simplify checkout. By reducing form fields, adding trust signals, and offering 'One-Click' login options, we help you capture more sales from your Pune traffic." },
  { q: "Why should I choose Growthik Media over a generic web dev house?", a: "Most dev houses build sites; we build businesses. We combine technical excellence with a deep understanding of e-commerce marketing, ensuring your store is technically perfect and marketing-ready from day one." },
];

export const EMAIL_MARKETING_FAQ: FAQItem[] = [
  { q: "Why is email marketing still effective for Pune businesses in 2026?", a: "Email is the only channel you truly own. With an average ROI of 36x, it allows you to nurture relationships with your Pune customers without being at the mercy of social media algorithm changes." },
  { q: "Which email marketing platforms do you specialize in?", a: "We work with top-tier platforms like Klaviyo, Mailchimp, and Brevo. We choose the platform that best fits your business model—Klaviyo for E-commerce or Mailchimp for Pune-based service providers." },
  { q: "How do you build and grow a high-quality email list for my Pune brand?", a: "We never buy lists. We build them organically using high-value 'Lead Magnets,' exit-intent popups, and strategic opt-ins on your website, ensuring every subscriber is a genuine potential customer." },
  { q: "What are 'Email Automations' and why does my business need them?", a: "Automations are trigger-based emails—like 'Welcome Series' or 'Abandoned Cart' reminders—that work for you 24/7. They ensure you send the right message at the right time without any manual effort." },
  { q: "How do you ensure my emails don't end up in the 'Spam' folder?", a: "We focus on 'Deliverability.' This involve setting up proper SPF, DKIM, and DMARC records, maintaining a clean list, and producing high-engagement content that email providers trust." },
  { q: "How much does a managed email marketing campaign cost in Pune?", a: "Management starts from ₹15,000/month. This covers strategy, design, copywriting, and monthly performance reporting, ensuring email is a consistent revenue driver for your brand." },
  { q: "Do you handle the copywriting and design for the emails?", a: "Yes, we provide end-to-end service. Our copywriters focus on persuasive, personalized messaging, while our designers create mobile-first layouts that reflect your brand identity." },
  { q: "How often should my Pune business be sending emails to its list?", a: "Quality over quantity. We typically recommend 1-2 value-driven newsletters per week, supplemented by automated flows. We find the 'Sweet Spot' that keeps you top-of-mind without annoying your audience." },
  { q: "What is 'Segmentation' and how does it improve my results?", a: "Segmentation divides your list based on behavior or demographics. By sending a specific offer to someone in Kochi vs someone in Pune, you increase relevance and conversion rates significantly." },
  { q: "How do you track the success and ROI of email marketing?", a: "We track Open Rates, Click-Through Rates, and most importantly, actual Revenue generated. We provide custom GA4-linked reports so you can see exactly how many Pune sales came from email." },
  { q: "Can email marketing help with customer retention for my Pune startup?", a: "Absolutely. Email is the best tool for 'Win-Back' campaigns and customer loyalty programs, increasing the Lifetime Value (LTV) of every customer you acquire in the Pune market." },
  { q: "Do you handle 'Cold Email' outreach for B2B companies?", a: "Yes, but we do it strategically. We focus on highly personalized, low-volume outreach that builds genuine relationships with decision-makers in Pune's IT and manufacturing hubs." },
  { q: "What is A/B testing in email and why is it important?", a: "We test subject lines, imagery, and 'Calls to Action' to see what resonates best with your Pune audience. This data-led approach allows us to constantly improve your email performance over time." },
  { q: "Is email marketing compliant with data privacy laws like GDPR?", a: "Yes, we ensure 100% compliance with data privacy regulations. We manage unsubscribes correctly and ensure all data collection is transparent and ethical for your Pune brand." },
  { q: "Why choose Growthik Media for email marketing over an in-house hire?", a: "You get a team of experts—strategists, copywriters, and deliverability specialists—for the price of a junior hire. We bring best-of-breed tools and experience from multiple industries to your Pune business." },
];

export const DIGITAL_MARKETING_FAQ: FAQItem[] = [
  { q: "What does a full-service digital marketing agency in Pune do?", a: "A full-service agency like Growthik Media manages your entire online presence — from SEO and Google Ads to social media, content, and email marketing. We build an integrated 'Growth System' that generates consistent leads rather than managing multiple disconnected vendors." },
  { q: "How do I know if my Pune business needs digital marketing?", a: "If your competitors appear before you on Google, your phone isn't ringing from online inquiries, or you're spending on ads without knowing your ROI — you need a strategic digital marketing partner. We offer a free audit that reveals exactly where revenue is being lost." },
  { q: "What is the first step when hiring Growthik Media for digital marketing?", a: "We begin with a 'Discovery & Audit' session where we analyze your current digital footprint, competitive landscape in Pune, and business goals. This produces a 90-day Growth Roadmap with clear priorities and projected ROI." },
  { q: "How much should a Pune SME spend on digital marketing per month?", a: "We recommend a minimum of ₹20,000–₹50,000/month for a meaningful, multi-channel campaign. For businesses in competitive sectors like real estate or IT in Hinjewadi or Baner, budgets of ₹75,000+ unlock significantly higher reach and returns." },
  { q: "What digital marketing channels work best for Pune businesses?", a: "It depends on your audience. B2C businesses thrive on Instagram, Meta Ads, and Local SEO. B2B firms in IT parks succeed most with LinkedIn, Google Search Ads, and Content Marketing. We mix channels strategically based on where your ideal customer actually spends time." },
  { q: "Can digital marketing work for offline Pune businesses?", a: "Absolutely. Local SEO and Google Ads are specifically designed to drive foot traffic and phone calls to physical locations. We help businesses from Kothrud bakeries to Wakad fitness studios generate walk-in customers digitally." },
  { q: "Do you offer a trial or short-term digital marketing contract?", a: "We offer 3-month starter engagements so you can see results before committing long-term. SEO requires 6+ months for full impact, but paid campaigns can show ROI within the first 30 days to build your confidence early." },
];

export const PERFORMANCE_MARKETING_FAQ: FAQItem[] = [
  { q: "What is performance marketing and how is it different from traditional digital marketing?", a: "Performance marketing means you only pay for measurable outcomes — leads, sales, or signups. Unlike brand campaigns that charge for impressions, every rupee we spend is tied to a specific, trackable business result for your Pune brand." },
  { q: "Which platforms do you use for performance marketing?", a: "We run campaigns across Google Search, Google Shopping, Meta (Facebook & Instagram), LinkedIn, and YouTube. Platform selection is data-driven, based on where your ideal Pune customer is most likely to convert." },
  { q: "How do you track ROAS (Return on Ad Spend) accurately?", a: "We implement conversion tracking via GTM and GA4 with server-side attribution where possible. This eliminates the iOS privacy gap and gives us accurate data on which campaigns, audiences, and creatives drive real revenue." },
  { q: "How quickly can I expect leads with performance marketing?", a: "Within 48-72 hours of launching paid campaigns, you'll see initial inquiries. The learning phase (7-14 days) refines targeting, and by week 3-4, campaigns are performing at their optimized baseline with consistent cost-per-lead metrics." },
  { q: "Do you work on a percentage-of-spend or flat-fee model?", a: "We typically offer flat management fees to align incentives — we don't benefit from you spending more. Our goal is to reduce your CPA while maintaining lead quality, not inflate budgets for higher commissions." },
  { q: "Can performance marketing help a Pune B2B company generate enterprise leads?", a: "Yes. We combine LinkedIn Lead Gen Forms with Google Search Intent targeting to reach CFOs, procurement heads, and decision-makers in Pune's IT and manufacturing hubs. B2B performance marketing is a core specialty for us." },
  { q: "What is CPA (Cost Per Acquisition) and how do you optimize it?", a: "CPA is the total cost to acquire one customer. We lower it through rigorous A/B testing of ad copy, landing pages, and audiences, combined with regular negative keyword pruning and bid strategy optimization." },
];

export const SOCIAL_PROMOTIONS_FAQ: FAQItem[] = [
  { q: "What is the difference between social media management and social media promotions?", a: "Social media management is the organic side — posting content, engaging with followers, growing your community. Social media promotions are paid campaigns that amplify your content to reach new audiences beyond your existing followers in Pune and beyond." },
  { q: "How do paid social promotions boost reach for Pune businesses?", a: "Organic reach on platforms like Instagram is below 5% of your followers. Paid promotions boost your best content to thousands of targeted users in specific Pune neighborhoods or interest groups, guaranteeing visibility for the investment." },
  { q: "What social platforms should my Pune brand run promotions on?", a: "For local consumer brands, Instagram and Facebook are the highest ROI platforms. For B2B, LinkedIn Sponsored Posts reach decision-makers in Hinjewadi. For younger audiences, YouTube Pre-Roll and Instagram Reels ads are highly effective." },
  { q: "How much does a social media promotion campaign cost in Pune?", a: "Promotion campaigns can start as low as ₹5,000 in ad spend. For substantial reach and lead generation, ₹15,000–₹50,000/month delivers measurable results. We optimize your budget for maximum Cost-Per-Engagement." },
  { q: "Can you create the creatives for social promotions?", a: "Yes, our in-house design team creates high-performing ad creatives — from static images and carousels to short-form video. We tailor visuals for the platform and target audience to maximize engagement and conversion rates." },
  { q: "How do you measure the success of social promotions?", a: "We track Reach, Impressions, Click-Through Rate, Cost Per Click, and most importantly — Conversions (leads, sales, or page visits). All metrics are tied to your business goals, not just vanity numbers like likes." },
  { q: "Is organic content or paid promotion better for my Pune brand?", a: "Both serve different purposes. Organic builds long-term trust and community. Paid promotion delivers immediate, measurable reach. The winning strategy for Pune brands is a hybrid — consistent organic plus strategic paid amplification." },
];

export const WHATSAPP_MARKETING_FAQ: FAQItem[] = [
  { q: "What is WhatsApp Business API and why do Pune businesses need it?", a: "The WhatsApp Business API is the official, verified, and scalable version of WhatsApp that allows sending automated messages, building chatbots, and running broadcast campaigns to thousands of contacts. It prevents account bans and is essential for any Pune business doing high-volume outreach." },
  { q: "Is bulk WhatsApp marketing legal in India?", a: "Yes, when done through the official WhatsApp Business API with proper opt-in and consent from users, it is fully legal and compliant with WhatsApp's terms of service. We ensure all our Pune client campaigns follow these guidelines strictly." },
  { q: "What is the difference between the WhatsApp Business App and the API?", a: "The free Business App limits you to one device and manual messaging. The API allows multi-agent access, automated chatbot flows, CRM integration, and bulk messaging at scale through approved Business Solution Providers (BSPs)." },
  { q: "How do you build a WhatsApp subscriber list for my Pune business?", a: "We use multiple opt-in channels: website pop-ups, QR codes placed in your Pune store, lead forms, social media, and Click-to-WhatsApp Meta Ads. Every contact on your list has explicitly opted in, ensuring high engagement rates." },
  { q: "What types of messages can be sent via WhatsApp marketing?", a: "You can send promotional offers, appointment reminders, order confirmations, shipping updates, lead nurture sequences, and event invitations. For interactive campaigns, we build chatbots that qualify leads and book appointments automatically." },
  { q: "How is WhatsApp marketing better than email or SMS for Pune brands?", a: "WhatsApp has a 98% open rate compared to 20% for email. Messages are seen within minutes on a platform users check 30+ times per day. For Pune audiences who prefer WhatsApp for personal communication, marketing here feels natural and non-intrusive." },
  { q: "Can WhatsApp be integrated with my existing CRM?", a: "Yes, we integrate WhatsApp marketing with Zoho, HubSpot, Salesforce, and other CRMs. Every new lead from WhatsApp is automatically added to your sales pipeline with all context and conversation history preserved." },
];

export const SMS_MARKETING_FAQ: FAQItem[] = [
  { q: "Is bulk SMS marketing still effective in 2026?", a: "Absolutely. SMS has a 98% open rate and 90% of messages are read within 3 minutes of delivery. For time-sensitive offers, appointment reminders, and transactional alerts targeted at Pune customers, SMS remains one of the most cost-effective channels available." },
  { q: "What is the difference between promotional SMS and transactional SMS?", a: "Promotional SMS is used for marketing offers and can only be sent during permitted hours. Transactional SMS delivers critical information like OTPs, booking confirmations, and payment receipts and can be sent 24/7. We manage both for our Pune clients." },
  { q: "Do I need TRAI DLT registration for bulk SMS in India?", a: "Yes, TRAI's Distributed Ledger Technology (DLT) registration is mandatory for all bulk SMS senders in India. We handle the complete DLT entity and template registration process on your behalf, ensuring your Pune campaigns are fully compliant." },
  { q: "How many SMS can I send and at what cost in Pune?", a: "There is no firm limit via licensed providers. Costs in India typically range from ₹0.10 to ₹0.25 per SMS. We negotiate best-in-market rates for our Pune clients and provide a complete analytics dashboard to track delivery and ROI." },
  { q: "Can I personalize bulk SMS messages for my Pune customers?", a: "Yes. We use dynamic fields to insert customer names, order IDs, or appointment times. Personalized SMS messages have 35% higher click-through rates than generic broadcasts, making them far more effective for conversions." },
  { q: "What industries in Pune benefit most from SMS marketing?", a: "Real estate firms in Kalyani Nagar, healthcare clinics in Aundh, retail shops in Camp, education institutes, and restaurants across Pune all see strong ROI from SMS marketing. Any business with a customer list can benefit from strategic SMS campaigns." },
  { q: "How do I measure the ROI of my SMS marketing campaign?", a: "We provide detailed reports including delivery rates, click-through rates on tracked links, and conversions. By integrating with your CRM or landing pages, we can attribute actual revenue to each SMS campaign, giving you a clear ROI picture." },
];

export const INFLUENCER_FAQ: FAQItem[] = [
  { q: "What types of influencers are best for Pune-based brands?", a: "Micro-influencers (10K–100K followers) with a genuine Pune-based audience often outperform mega-influencers. They have higher engagement rates and their followers trust their recommendations. We identify influencers in your exact niche — from Pune foodie channels to Hinjewadi tech creators." },
  { q: "How do you vet influencers to avoid fake followers?", a: "We use professional analytics tools to check audience authenticity scores, engagement ratios, comment quality, and follower growth patterns. We reject any influencer with fake engagement spikes, ensuring your Pune brand partners only with authentic creators." },
  { q: "How much does influencer marketing cost in Pune?", a: "Micro-influencer campaigns in Pune typically cost ₹5,000–₹30,000 per creator per post. Niche-specific macro-influencers can range from ₹50,000–₹2,00,000+. We optimize your budget by selecting the best-fit creators for maximum ROI." },
  { q: "What is the process for running an influencer campaign with Growthik Media?", a: "We handle everything: identifying relevant Pune influencers, negotiating contracts, briefing creators, reviewing content before posting, managing the campaign timeline, and providing a full ROI report on deliverables, reach, and business outcomes." },
  { q: "Can influencer marketing work for B2B companies in Pune?", a: "Yes, LinkedIn micro-influencers and thought leaders in the IT and manufacturing space are very effective for B2B. A respected voice in Hinjewadi's tech community endorsing your SaaS product generates high-quality B2B leads." },
  { q: "How do you measure the success of an influencer campaign?", a: "We track Reach, Impressions, Engagement Rate, Story Views, Link Clicks, and most importantly, attributed Conversions via unique discount codes or UTM-tracked links. We provide a post-campaign report with a clear cost-per-result breakdown." },
  { q: "What platforms do you run influencer campaigns on for Pune brands?", a: "Primarily Instagram and YouTube for consumer brands. LinkedIn for B2B. We also leverage emerging platforms for campaigns targeting regional Pune content. Platform selection depends on your target demographic." },
];

export const MEDIA_PLANNING_FAQ: FAQItem[] = [
  { q: "What is media planning and buying and why does my Pune business need it?", a: "Media planning is the strategic process of identifying the best channels, timing, and audience segments to reach your target customer. Media buying is the execution — purchasing ad space at the best possible rates. Together, they ensure your budget generates maximum impact across Pune's competitive market." },
  { q: "Which media channels do you plan and buy for Pune businesses?", a: "We manage digital media across Google, Meta, LinkedIn, YouTube, and programmatic DSPs. We also coordinate with OOH (hoarding and transit ads near Camp or Wakad), radio, and digital-out-of-home (DOOH) providers for integrated 360-degree Pune campaigns." },
  { q: "What is programmatic advertising and how does it work?", a: "Programmatic advertising uses algorithms to automatically buy digital ad space in real-time auctions at the lowest possible price. It allows your ads to appear on thousands of premium websites targeting specific Pune users by demographics, behavior, and intent, far more efficiently than manual buying." },
  { q: "How do you calculate the optimal media mix for my brand?", a: "We start with your business goals and target audience, then analyze channel-specific reach data for Pune. We use attribution modeling to understand the actual customer journey and allocate budget proportionally to channels that drive the most conversions at the lowest CPA." },
  { q: "Do you negotiate media buying rates for your Pune clients?", a: "Yes, our buying relationships and purchase volumes allow us to secure rates below open-market prices. For digital programmatic buys, we leverage sophisticated bidding algorithms that continuously lower your effective CPM while maintaining quality reach." },
  { q: "How often is the media plan reviewed and adjusted?", a: "We review campaign performance weekly and optimize bids, creatives, and channel allocation dynamically. Monthly strategy reviews with you assess overall budget effectiveness and reallocate spend to the top-performing channels for your Pune business." },
  { q: "Can media planning help improve brand awareness in Pune?", a: "Absolutely. A coordinated media plan that combines digital display, social media, and OOH creates a strong omnipresence effect in Pune. When a prospect sees your brand across multiple touchpoints — online, on their commute, and on social — they trust and remember you significantly more." },
];

export const YOUTUBE_SEO_FAQ: FAQItem[] = [
  { q: "What is YouTube SEO and why is it important for my Pune business?", a: "YouTube SEO optimizes your video content to rank higher in YouTube and Google search results. With over 500 hours of video uploaded per minute, strategic optimization ensures your Pune brand videos appear when potential customers search for your services, driving free, organic views and leads." },
  { q: "What are the most important YouTube ranking factors?", a: "Key factors include Watch Time and Session Time (how long viewers stay), Click-Through Rate (how many click your thumbnail), keyword-rich titles, descriptions and tags, video engagement (likes, comments, shares), and channel authority (subscribers and upload consistency)." },
  { q: "How do you conduct keyword research for YouTube?", a: "We use tools like TubeBuddy, VidIQ, and Google Trends to find high-volume, low-competition keywords relevant to your Pune business. We focus on search intent keywords — queries where users are actively looking for a solution you provide." },
  { q: "Do you create the video content or only optimize existing videos?", a: "We do both. We can optimize, re-title, and restructure existing video metadata for immediate ranking improvements. For new content, we provide detailed content briefs, scripts, and production guidance to ensure videos are built for ranking from the start." },
  { q: "How long does it take to rank a YouTube video for Pune searches?", a: "Optimization of metadata and thumbnails can improve impressions within days. Sustained ranking for competitive keywords takes 1-3 months as YouTube's algorithm assesses watch metrics. Consistent uploads and engagement accelerate this timeline significantly." },
  { q: "What is YouTube thumbnail optimization and why does it matter?", a: "Your thumbnail is your video's first impression. It directly impacts CTR, which is a primary ranking signal. We design custom, high-contrast thumbnails with clear text and faces to maximize clicks for your Pune brand's content." },
  { q: "Can YouTube SEO generate business leads in Pune?", a: "Yes. By ranking for search terms like 'best digital marketing agency Pune' or 'website development tips for startups,' your videos reach high-intent viewers who are your ideal customers. We include strategic CTAs, end screens, and links to convert viewers into inquiries." },
];

export const POLITICAL_MARKETING_FAQ: FAQItem[] = [
  { q: "What is political digital marketing and what does it involve?", a: "Political digital marketing uses data-driven online strategies — including social media, targeted ads, content marketing, and voter sentiment analysis — to build a candidate's brand, mobilize supporters, and reach undecided voters during election campaigns across Pune and Maharashtra." },
  { q: "How can digital marketing help my election campaign in Pune?", a: "Digital marketing allows hyper-local targeting to reach voters in specific wards or constituencies. We can segment messaging by age group, locality, and issue priorities. This precision — reaching the right voter with the right message — is far more effective than traditional mass-media campaigning." },
  { q: "What platforms are most effective for political campaigns in Pune?", a: "WhatsApp is critical for ground-level voter communication and mass outreach. Facebook and Instagram reach older and middle-aged voters. YouTube allows impactful long-form storytelling. We also leverage local Marathi-language social groups and content platforms." },
  { q: "Can you manage a political party's social media presence in Maharashtra?", a: "Yes, we provide complete social media management for political parties and candidates — daily content creation, community management, crisis communication, and platform-specific strategies for Vidhan Sabha and Lok Sabha constituencies across Maharashtra." },
  { q: "What is voter sentiment analysis and how do you use it?", a: "We monitor social mentions, comments, and news coverage to map public sentiment toward a candidate or policy. This data identifies which issues resonate or create backlash, allowing campaign messaging to be adjusted in real-time for maximum positive impact." },
  { q: "Is political digital marketing expensive and what is the ROI?", a: "Digital campaigning is significantly more cost-effective than hoardings, rallies, or TV ads. The ROI is measured in votes and visibility. A targeted digital strategy can reach 10x more potential voters for the same investment as traditional media buys." },
  { q: "How do you ensure ethical and legal compliance in political campaigns?", a: "We strictly adhere to the Model Code of Conduct and Election Commission of India guidelines. All paid political advertisements are properly tagged. We do not engage in misinformation or negative campaigning that violates ethical standards." },
];

export const WORDPRESS_FAQ: FAQItem[] = [
  { q: "Why choose WordPress for my Pune business website?", a: "WordPress powers 43% of all websites globally and offers unmatched flexibility. For Pune SMBs, it provides a cost-effective, scalable solution with thousands of plugins, a robust CMS for self-editing, and strong SEO capabilities — all without requiring ongoing developer dependency." },
  { q: "How much does a custom WordPress website cost in Pune?", a: "A professionally designed WordPress site for a Pune business typically ranges from ₹20,000 to ₹80,000 depending on page count, custom functionality, and design complexity. WooCommerce stores cost ₹35,000–₹1,50,000. We provide transparent quotes with no hidden charges." },
  { q: "How long does it take to build a WordPress website?", a: "A standard 5-10 page corporate WordPress website takes 3-5 weeks. A complex multi-page site with custom features or WooCommerce takes 6-10 weeks. We provide a detailed project timeline in our proposal so you know exactly when to expect your Pune business to go live." },
  { q: "Can I update my WordPress website myself after it is built?", a: "Yes, that's one of WordPress's greatest strengths. We provide dedicated training sessions so your Pune team can update pages, add blog posts, and manage products independently without any coding knowledge. We also provide a documentation guide for your specific setup." },
  { q: "How do you ensure WordPress website security in Pune?", a: "We implement SSL certificates, security plugins (like Wordfence), strong admin credentials, regular database backups, and core/plugin update schedules. For e-Commerce, we ensure PCI compliance. Security hardening is included in every WordPress project we deliver." },
  { q: "Will my WordPress site be SEO-optimized from launch?", a: "Yes. We install and configure Yoast or Rank Math SEO, optimize page speed, implement proper heading hierarchies, add JSON-LD schema markup, create XML sitemaps, and ensure your site is submission-ready for Google Search Console on day one." },
  { q: "Do you provide ongoing WordPress maintenance and support in Pune?", a: "Yes, our monthly maintenance plans (starting ₹5,000/month) include core and plugin updates, security monitoring, performance checks, uptime monitoring, and a support ticket system for any technical issues — giving you peace of mind to focus on your business." },
];

export const SOFTWARE_DEV_FAQ: FAQItem[] = [
  { q: "What types of custom software does Growthik Media develop for Pune businesses?", a: "We build a wide range of software: CRM systems, ERP solutions, SaaS platforms, internal workflow tools, API integrations, data dashboards, and AI-powered applications. Our focus is on solving real business problems that off-the-shelf software cannot address for Pune enterprises." },
  { q: "What technology stack do you use for custom software development?", a: "We primarily use Next.js and React for frontends, Node.js or Python for backends, PostgreSQL or MongoDB for databases, and deploy on AWS, Vercel, or Google Cloud. We choose the stack based on your performance, scalability, and budget requirements." },
  { q: "How long does custom software development take?", a: "An MVP (Minimum Viable Product) typically takes 8-16 weeks. Full enterprise applications take 4-12 months. We use agile sprints so you see working software every 2 weeks and can provide feedback continuously throughout the Pune development process." },
  { q: "How do you ensure the quality and reliability of the software?", a: "We follow a rigorous QA process including unit testing, integration testing, user acceptance testing (UAT), and performance load testing. Every deployment goes through a staging environment before going live to ensure zero-disruption releases for your Pune business." },
  { q: "What does custom software cost in Pune compared to off-the-shelf solutions?", a: "While initial development costs (₹2,00,000–₹20,00,000+) are higher than subscriptions, custom software eliminates ongoing SaaS fees, fits your exact workflow, and becomes a competitive advantage. For Pune businesses at scale, it's often more economical over a 3-year horizon." },
  { q: "Do you build software integrations with existing tools like Zoho or Tally?", a: "Yes, API integration is a core specialty. We connect custom software with Zoho CRM, Tally ERP, payment gateways (Razorpay), WhatsApp Business API, and third-party logistics systems, creating a unified digital ecosystem for your Pune operations." },
  { q: "What happens after the software is launched — do you provide support?", a: "Yes, we offer SLA-backed post-launch support and maintenance contracts. This covers bug fixes, performance monitoring, security patches, and feature enhancements as your Pune business evolves and your software requirements grow." },
];

export const MOBILE_APP_FAQ: FAQItem[] = [
  { q: "Should I build a native app (iOS/Android) or a cross-platform app for my Pune business?", a: "For most Pune SMBs and startups, cross-platform frameworks like React Native or Flutter deliver 90% of native performance at 50-60% of the development cost. Native development is recommended only when your app requires deep OS-level integrations like AR or complex hardware access." },
  { q: "How much does mobile app development cost in Pune?", a: "Simple apps (5-10 screens) cost ₹1,50,000–₹4,00,000. Medium-complexity apps with backend, APIs, and user accounts range from ₹4,00,000–₹12,00,000. Complex marketplace or SaaS apps with advanced features cost ₹12,00,000+. We provide detailed quotes after reviewing your specifications." },
  { q: "How long does it take to develop and launch a mobile app?", a: "An MVP app with core features typically takes 10-16 weeks. Full-featured apps take 4-8 months. We recommend an MVP-first approach for Pune startups — launch quickly, gather user feedback, and iterate. This reduces financial risk and time-to-market significantly." },
  { q: "What is App Store Optimization (ASO) and do you provide it?", a: "Yes. ASO is the mobile equivalent of SEO — optimizing your app's title, description, keywords, screenshots, and reviews to rank higher in the App Store and Google Play search results. We implement ASO from launch to maximize organic app installs for your Pune brand." },
  { q: "How do you handle app security and user data protection?", a: "We implement industry best practices: encrypted data transmission (HTTPS/TLS), secure API authentication (JWT/OAuth), local data encryption, and regular security penetration testing. We ensure compliance with IT Act 2000 requirements relevant for Indian app businesses." },
  { q: "Can you integrate payment gateways like Razorpay into my app?", a: "Yes, we have extensive experience integrating Razorpay, PayU, and other Indian payment gateways into mobile apps. We handle the complete payment flow including recurring subscriptions, refunds, and split payments for marketplace apps targeting Pune customers." },
  { q: "Do you provide post-launch support and app updates?", a: "Yes, we offer monthly retainer plans that cover OS update compatibility testing, performance monitoring, bug fixes, and feature additions. Mobile platforms update frequently, and an unsupported app quickly becomes unusable — our maintenance plans prevent this." },
];

export const WEBSITE_DESIGN_FAQ: FAQItem[] = [
  { q: "What makes a great website design for Pune businesses?", a: "An effective website design for Pune combines fast load times (essential for mobile users), clear conversion paths, local trust signals, and stunning visuals. It must communicate your value proposition within 3 seconds and guide visitors intuitively toward calling, booking, or buying." },
  { q: "Do you follow a mobile-first approach for website design?", a: "Absolutely. Over 80% of Indian internet users access the web via smartphones. Every website we design starts with the mobile experience first, then scales to desktop. This ensures perfect performance on the devices your Pune customers actually use." },
  { q: "What is the difference between UI design and UX design?", a: "UI (User Interface) is what the website looks like — colors, typography, buttons, and visual hierarchy. UX (User Experience) is how it feels to use — the logic of navigation, speed, and how easily a Pune visitor can find what they need and take action." },
  { q: "How long does a website design project take?", a: "A complete website design (wireframing, prototyping, design handoff, and revisions) typically takes 2-4 weeks before development begins. We use Figma for visual prototyping, giving you a fully clickable preview to approve before a single line of code is written." },
  { q: "How many design revisions do I get?", a: "Our standard process includes 2 rounds of design revisions at each stage (wireframe and final design). This ensures your Pune brand's vision is captured accurately without scope-creep that delays the project launch." },
  { q: "Do you design logos and brand identity as well?", a: "Yes, our branding team creates logos, color palettes, typography systems, and brand guidelines that are then applied consistently across the website. For Pune businesses launching new brands, we offer bundled brand identity and web design packages." },
  { q: "Will my website design help with SEO?", a: "Significantly. A well-structured design with fast load speeds, proper heading hierarchy, clean HTML, and optimized images directly improves your Google rankings. We ensure every website we design passes Core Web Vitals and is technically optimized for Pune-based search intent from day one." },
];

