"use client";

import React, { useState, useEffect } from "react";
import {
  FiMessageCircle,
  FiUser,
  FiCalendar,
  FiChevronRight,
  FiChevronDown,
  FiMail,
  FiPhone,
  FiClock,
  FiSearch,
  FiCpu,
} from "react-icons/fi";
import { motion, AnimatePresence } from "framer-motion";

interface ChatMessage {
  id: string;
  text: string;
  sender: string;
  createdAt: string;
}

interface ChatSession {
  id: string;
  createdAt: string;
  messages: ChatMessage[];
}

interface ChatLead {
  id: string;
  name: string;
  email: string;
  phone: string;
  createdAt: string;
  sessions: ChatSession[];
}

export default function ChatIntelligence() {
  const [leads, setLeads] = useState<ChatLead[]>([]);
  const [loading, setLoading] = useState(true);
  const [expandedLead, setExpandedLead] = useState<string | null>(null);
  const [selectedSession, setSelectedSession] = useState<string | null>(null);
  const [searchTerm, setSearchTerm] = useState("");

  useEffect(() => {
    fetchLogs();
  }, []);

  const fetchLogs = async () => {
    try {
      const response = await fetch("/api/chat/logs");
      const data = await response.json();
      setLeads(data);
    } catch (error) {
      console.error("Error fetching logs:", error);
    } finally {
      setLoading(false);
    }
  };

  const filteredLeads = leads.filter(
    (lead) =>
      lead.name.toLowerCase().includes(searchTerm.toLowerCase()) ||
      lead.email.toLowerCase().includes(searchTerm.toLowerCase()) ||
      lead.phone.includes(searchTerm),
  );

  return (
    <div className="p-4 bg-white dark:bg-gray-900 rounded-2xl border border-gray-100 dark:border-gray-800">
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center mb-8 gap-4 px-2">
        <div>
          <h2 className="text-2xl font-bold text-gray-800 dark:text-white flex items-center gap-2">
            Chat <span className="text-blue-500">Intelligence</span>
          </h2>
          <p className="text-gray-500 text-sm mt-1">
            Analyze lead conversations generated by Growthik AI.
          </p>
        </div>

        <div className="relative w-full md:w-64">
          <FiSearch className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400" />
          <input
            type="text"
            placeholder="Search leads..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="w-full bg-gray-50 dark:bg-gray-800 border border-gray-200 dark:border-gray-700 pl-10 pr-4 py-2 text-sm rounded-xl focus:ring-2 focus:ring-blue-500 outline-none transition-all"
          />
        </div>
      </div>

      {loading ? (
        <div className="flex justify-center items-center h-64">
          <div className="animate-spin rounded-full h-10 w-10 border-t-2 border-b-2 border-blue-500"></div>
        </div>
      ) : (
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
          {/* Leads List */}
          <div className="lg:col-span-5 space-y-3 max-h-[60vh] overflow-y-auto pr-2 custom-scrollbar">
            {filteredLeads.map((lead) => (
              <div
                key={lead.id}
                className={`rounded-xl border transition-all duration-300 ${
                  expandedLead === lead.id
                    ? "border-blue-500 bg-blue-50/10"
                    : "border-gray-100 dark:border-gray-800 bg-gray-50/50 dark:bg-gray-800/30 hover:border-blue-200 dark:hover:border-blue-900"
                }`}
              >
                <button
                  onClick={() =>
                    setExpandedLead(expandedLead === lead.id ? null : lead.id)
                  }
                  className="w-full p-4 text-left"
                >
                  <div className="flex justify-between items-center">
                    <div className="flex items-center gap-3">
                      <div className="w-10 h-10 rounded-full bg-blue-500/10 text-blue-500 flex items-center justify-center font-bold text-sm">
                        {lead.name.charAt(0)}
                      </div>
                      <div>
                        <h3 className="font-bold text-gray-800 dark:text-gray-100 leading-tight">
                          {lead.name}
                        </h3>
                        <p className="text-[10px] text-gray-500 mt-1">
                          {lead.email}
                        </p>
                      </div>
                    </div>
                    <div className="text-right flex flex-col items-end">
                      <span className="text-[10px] text-gray-400 mb-1">
                        {new Date(lead.createdAt).toLocaleDateString()}
                      </span>
                      {expandedLead === lead.id ? (
                        <FiChevronDown />
                      ) : (
                        <FiChevronRight />
                      )}
                    </div>
                  </div>
                </button>

                <AnimatePresence>
                  {expandedLead === lead.id && (
                    <motion.div
                      initial={{ height: 0, opacity: 0 }}
                      animate={{ height: "auto", opacity: 1 }}
                      exit={{ height: 0, opacity: 0 }}
                      className="overflow-hidden bg-white/50 dark:bg-black/20 border-t border-gray-100 dark:border-gray-800 rounded-b-xl"
                    >
                      <div className="p-3 space-y-1">
                        {lead.sessions.map((session, idx) => (
                          <button
                            key={session.id}
                            onClick={() => setSelectedSession(session.id)}
                            className={`w-full p-3 rounded-lg flex justify-between items-center transition-all ${
                              selectedSession === session.id
                                ? "bg-blue-500 text-white shadow-lg shadow-blue-500/20"
                                : "hover:bg-gray-100 dark:hover:bg-gray-700 text-gray-700 dark:text-gray-300"
                            }`}
                          >
                            <div className="flex items-center gap-2">
                              <FiMessageCircle className="w-3.5 h-3.5" />
                              <span className="text-xs font-semibold">
                                Session {lead.sessions.length - idx}
                              </span>
                            </div>
                            <span className="text-[9px] opacity-70">
                              {new Date(session.createdAt).toLocaleTimeString(
                                [],
                                { hour: "2-digit", minute: "2-digit" },
                              )}
                            </span>
                          </button>
                        ))}
                      </div>
                    </motion.div>
                  )}
                </AnimatePresence>
              </div>
            ))}

            {filteredLeads.length === 0 && (
              <div className="text-center py-12 border-2 border-dashed border-gray-100 dark:border-gray-800 rounded-2xl">
                <FiMessageCircle className="w-8 h-8 text-gray-300 mx-auto mb-3" />
                <p className="text-gray-500 text-sm">No conversations found.</p>
              </div>
            )}
          </div>

          {/* Conversation View */}
          <div className="lg:col-span-7">
            {selectedSession ? (
              <div className="bg-gray-50 dark:bg-gray-800/50 rounded-2xl border border-gray-100 dark:border-gray-700 h-[60vh] flex flex-col shadow-inner">
                <div className="p-4 border-b border-gray-100 dark:border-gray-700 flex justify-between items-center bg-white dark:bg-gray-800 rounded-t-2xl">
                  <div className="flex items-center gap-3">
                    <div className="bg-green-500/10 text-green-500 px-2 py-1 rounded text-[10px] font-bold uppercase tracking-wider">
                      Transcript
                    </div>
                  </div>
                  <div className="text-[10px] font-bold text-gray-400 uppercase tracking-widest flex items-center gap-1">
                    <FiClock />{" "}
                    {new Date(
                      leads
                        .find((l) =>
                          l.sessions.some((s) => s.id === selectedSession),
                        )
                        ?.sessions.find((s) => s.id === selectedSession)
                        ?.createdAt || "",
                    ).toLocaleTimeString()}
                  </div>
                </div>

                <div className="flex-1 overflow-y-auto p-4 space-y-4 custom-scrollbar">
                  {leads
                    .find((l) =>
                      l.sessions.some((s) => s.id === selectedSession),
                    )
                    ?.sessions.find((s) => s.id === selectedSession)
                    ?.messages.map((msg) => (
                      <div
                        key={msg.id}
                        className={`flex ${msg.sender === "user" ? "justify-end" : "justify-start"}`}
                      >
                        <div
                          className={`flex gap-3 max-w-[85%] ${msg.sender === "user" ? "flex-row-reverse" : "flex-row"}`}
                        >
                          <div
                            className={`w-7 h-7 rounded-lg flex items-center justify-center shrink-0 border mt-1 shadow-sm ${
                              msg.sender === "user"
                                ? "bg-white dark:bg-gray-700 text-gray-400 border-gray-100 dark:border-gray-600"
                                : "bg-blue-500 text-white border-blue-600"
                            }`}
                          >
                            {msg.sender === "user" ? (
                              <FiUser className="w-3.5 h-3.5" />
                            ) : (
                              <FiCpu className="w-3.5 h-3.5" />
                            )}
                          </div>
                          <div>
                            <div
                              className={`p-3 text-xs leading-relaxed rounded-2xl shadow-sm border ${
                                msg.sender === "user"
                                  ? "bg-white dark:bg-gray-700 border-gray-200 dark:border-gray-600 rounded-tr-none text-gray-800 dark:text-gray-100"
                                  : "bg-blue-500 border-blue-600 rounded-tl-none text-white shadow-blue-500/10"
                              }`}
                            >
                              {msg.text}
                            </div>
                            <span className="text-[8px] text-gray-400 mt-1 block px-2 font-medium">
                              {new Date(msg.createdAt).toLocaleTimeString([], {
                                hour: "2-digit",
                                minute: "2-digit",
                              })}
                            </span>
                          </div>
                        </div>
                      </div>
                    ))}
                </div>
              </div>
            ) : (
              <div className="bg-gray-50/50 dark:bg-gray-800/20 border-2 border-dashed border-gray-100 dark:border-gray-800 rounded-2xl h-[60vh] flex flex-col justify-center items-center text-center p-8">
                <div className="w-16 h-16 bg-white dark:bg-gray-800 rounded-2xl flex items-center justify-center mb-6 shadow-sm border border-gray-100 dark:border-gray-700">
                  <FiMessageCircle className="w-8 h-8 text-blue-500/20" />
                </div>
                <h3 className="font-bold text-gray-800 dark:text-white text-lg mb-2">
                  Ready for analysis
                </h3>
                <p className="text-xs text-gray-500 max-w-xs leading-relaxed">
                  Select a session transcript from the left to dive into user
                  interactions and identify growth opportunities.
                </p>
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
}
